### ISSUE TITLE
Bug on doc generation for Postman 

### ISSUE THREAD

**Issue by maiconmva** [knuckleswtf/scribe#137]
This is the doc comment for examples 

![image](https://user-images.githubusercontent.com/5194641/98259417-dcffb880-1f60-11eb-901d-6fe535e52e17.png)

this is how postman read:

![image](https://user-images.githubusercontent.com/5194641/98259666-2a7c2580-1f61-11eb-931f-d128dfc98db7.png)

this is how is generated the json collection info

![image](https://user-images.githubusercontent.com/5194641/98259753-45e73080-1f61-11eb-96c7-3649c6c4f9cd.png)

**Comment by shalvah** [comment]
That's not a bug. The values are URL-encoded. It's the same thing. If you don't encode them, your client (browser or Postman) does so before sending the request. See https://stackoverflow.com/a/40595/7370522

**Comment by maiconmva** [comment]
yea, i know, but this is json for import in postman ( this file is just for that), and postman cant read endcoded string..

this is how the same file was exported from postman, after fix inside postman:

![image](https://user-images.githubusercontent.com/5194641/98275186-20fbb900-1f73-11eb-8c2f-d8b2a0890d36.png)

i think that is a bug..

**Comment by shalvah** [comment]
It's not a bug.

Yes, it's JSON, but these are query parameters. They're going to be in a URL, so we go ahead and encode them. It doesn't look as good, but it's still correct. Do your requests fail when you try them in Postman?

**Comment by maiconmva** [comment]
no fail, but import wrong 

![image](https://user-images.githubusercontent.com/5194641/98277951-b3518c00-1f76-11eb-8058-8c11a430071a.png)

**Comment by shalvah** [comment]
That's not my question. When you send the request, does your backend complain? Does it not work the same either way?

**Comment by shalvah** [comment]
If not, then it's not a bug. The parameters are URL-encoded so that they can reliably work regardless of where they're used. Please stop harping on this.

**Comment by maiconmva** [comment]
its kind of funny

the script needs generate a json JUST for POSTMAN, and postman cannot read encoded string.

so what is for? 

anyway, this is my block of code to fix that, if anyone needs.

![image](https://user-images.githubusercontent.com/5194641/98280502-42ac6e80-1f7a-11eb-9b06-21cb45c6cad2.png)

**Comment by shalvah** [comment]
> the script needs generate a json JUST for POSTMAN, and postman cannot read encoded string.

Dude. You've confirmed yourself that the request works when you send it your backend. Which means Postman does read it. *It just doesn't look good to you*. You can open up a different conversation on not encoding the parameters if you like, but nothing you've said here is a BUG. It's intentional behaviour, and for good reason. 

I've tried to reason with you. Stop making a maintainer's life hard, for software they've laboured on and provided you with for free.

**Comment by shalvah** [comment]
My bad. I hate shutting down conversations with the maintainer card. However, you've refused to understand me at all, while insisting on your point. Even if you don't understand any explanation I've put forward, then just take this as an answer:

- a bug is unexpected behaviour
- there is no unexpected behaviour here. The parameters are encoded, and the request works.

This is all expected behaviour. Now if you think this behaviour should be changed, that's a different story. open a new issue explaining why.
