### ISSUE TITLE
Accessing auth()->user() from a FormRequest

### ISSUE THREAD

**Issue by chrisbeaver** [knuckleswtf/scribe#155]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I'm on Laravel 7 running:

knuckleswtf/pastel                      1.3.6     Write your API docs in Markdown and get them converted into pretty HTML🎨
knuckleswtf/scribe                      2.4.2     Generate API documentation for humans from your Laravel codebase.✍

I found a related and now closed issue here: https://github.com/knuckleswtf/scribe/issues/30

The author of the related issue was attempting to access Auth::user() from a FormRequest in a CI/CD environment. I'm attempting this with an active database. 

From this issue, I tried using a  [provided snippet](https://github.com/knuckleswtf/scribe/wiki/Helpful-strategies-(snippets)#authenticating-as-a-particular-user-for-response-calls)  to ensure my user was being authenticated. I reduced it to just fetching a user from the DB and authenticating. If I test a dd(auth()->user()) from that strategy it would dump the user I loaded.

![image](https://user-images.githubusercontent.com/5077917/101192230-c49ac080-3628-11eb-8a88-064e364bdaf8.png)

Swapping my strategy in to the config provides the expected result, although I'm not sure why it doesn't happen until the ninth route.

![image](https://user-images.githubusercontent.com/5077917/101192635-5a365000-3629-11eb-9aea-20fb85f0d382.png)

However, returning the $request rather than dumping the user generates an error. By the time I get to my extended FormRequest object, I attempt to access auth()->user() and it fails.

![image](https://user-images.githubusercontent.com/5077917/101191815-3292b800-3628-11eb-87ff-a9b20019f177.png)

I've configured the system to authenticate using a custom header and token. I provide a valid token to the config, but I get the same results if I provide an invalid token. 

So my question is, how can I tell if I'm actually authenticating when I run `artisan scribe:generate`?  And if I am authenticating, how can I access the authenticated user from a FormRequest object?

**Comment by shalvah** [comment]
Hmmm, I'm not sure `auth()->login()` would work correctly in your response call, because the response call crafts a new request, which doesn't have any user logged in.

https://github.com/knuckleswtf/scribe/blob/e58849abb4bd5371480fd32cc3fbc3718b7fc477/src/Extracting/Strategies/Responses/ResponseCalls.php#L133

Which is why, in the example snippet, I manually add the auth headers to the request, so when Laravel is handling the new request, it authenticates.

Also, there are two different things to consider:
- in the _response call_ strategy (to get a _response_), we make a full request that Laravel handles
- in the _form request_ strategy (to get _body parameters_), we don't make a request. We try to fake a request, and then execute the FormRequest ourselves to get the validation rule

https://github.com/knuckleswtf/scribe/blob/cb3fa1fa4c09447c65650a4ad7dff9e969f344c8/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php#L64-L73

WIthin a response call, if you send auth info with your request, like via a header or query param, `Auth::user()` should work.
Within the Form Request strategy, you can't be authenticated, so you'll get null.

**Comment by chrisbeaver** [comment]
You cleared this all up for me, thanks for taking the time to answer! 

I use the auth()->user() in my FormRequest object, so I just had to put a little work around in there and I got docs compiling. 

Thanks again. Nice work on this project!

**Comment by shalvah** [comment]
What workaround did you use?

**Comment by chrisbeaver** [comment]
I extended the GetFromFormRequest strategy.  My validation on some routes is dependent on the authenticated user's roles, so I access the auth()->user() helper from certain request objects.

```
<?php

namespace App\Util\Scribe;

class GetFromFormRequest extends \Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest
{
    public function __invoke(Route $route, ReflectionClass $controller, ReflectionFunctionAbstract $method, array $routeRules, array $alreadyExtractedData = []): array
    {
        $user = \App\Models\User::find(config('scribe.auth.user_id'));
        auth()->login($user);
        return parent::getBodyParametersFromFormRequest($method, $route);
    }
}
```
