### ISSUE TITLE
Docs for reusable controller. Multiple docs for single controller method

### ISSUE THREAD

**Issue by 4unkur** [knuckleswtf/scribe#176]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I have a single controller with 2 methods: store/destroy.  
This controller is called in 2 places for different models i.e.:  
```php
Route::post('api/bike/image', 'ImageController@store');
Route::post('api/part/image', 'ImageController@store');
```

Is it possible to have 2 different doc blocks for these?  
I tried to move the doc block from the controller to the routes file, but it did not work

**Comment by shalvah** [comment]
No, it's not supported. It's a very edge case, so it's unlikely it will be. You'll just have to write the docs in a context-aware manner.

**Comment by shalvah** [comment]
Alternatively, with v3, it may be possible to add routes manually, so you could have docs for one of the routes be autogenerated by Scribe and the other manually specified yourself.

**Comment by Luffyyy** [comment]
Is it possible with v3? I have an upsert function I'd like to just have a different name depending on the route. Perhaps having it override the data if it's defined in the Route::x function?

**Comment by shalvah** [comment]
Well, *this* is not doable in v3, but yes, you can add endpoints manually. If you'll look at the generated `.scribe` folder, there's an example custom endpoint YAML file there. You'd have to manually maintain that one yourself, but it works. 

Alternately, perhaps you could write your own custom strategies? Extend from the default ones, but fetch docblocks from route declaration instead of controller. Saying this because I'm not yet sure I want to be responsible for maintaining this functionality.
