### ISSUE TITLE
Is it posible to remove default url parameters?

### ISSUE THREAD

**Issue by JoseLuisToscanoPatata** [knuckleswtf/scribe#233]
- [x] I've read the  and I can't find details on how to achieve this.

Greetings, after searching for a while in the [scribe documentation] (https://scribe.rtfd.io), i havent found a way to stop scribe from creating URL parameters to my endpoints  based on the parameters that appear on the endpoint route on the api.php file (routes folder) on Laravel.

Do someone know if it is possible? Its kinda awfull that in the examples only appear string parameters when actually an integer (like an id) is needed:

![Captura](https://user-images.githubusercontent.com/60394586/120935661-1faa8e80-c704-11eb-868f-b0a928732e5e.JPG)

Sorry for the bad screenshot

**Comment by shalvah** [comment]
That's because of the paths Laravel generates for resource routes. In the current version of Scribe, you can manually add a `@urlParam message integer ...` yourself to override it.

In Scribe v3, Scribe will correctly generate what you expect— `id` with type "integer" and description "The ID of the message".

A release candidate for v3 should be out probably next week. Cleaning up the docs.

![Screenshot_20210606-192034~2](https://user-images.githubusercontent.com/14361073/120935811-79a75600-c6fc-11eb-961c-f8a4101facf0.jpg)

**Comment by shalvah** [comment]
Oh, and of course, if Scribe doesn't get it right, you can modify the data it generates, and it will respect that. (v3)

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3)!
