### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by dmalmeida** [knuckleswtf/scribe#243]
Hi

I am trying to put "Try it out" working and it works on all GET endpoints. But on POST endpoints(I only have login and logout, for now) , it gives "CSRF token mismatch".
I'm using Sanctum for Authenticate.
At Postman all is ok. I can login and logout without a problem.

Does anyone knows how to help me?
I have no experience with laravel.... this is my final project at university and I'm a little bit stucked in this.

Thanks and sorry about my english

**Comment by shalvah** [comment]
I don't have any experience with Sanctum, so I don't think I'll be able to help much. But when debugging issues like this, your best bet is to check the actual request being sent by "Try It Out". Check the Network tab. Then you can compare it to Postman's request. My guess is that because it's coming from the frontend, Laravel interprets this as an SPA request and looks for a CSRF token (which wasn't sent). I'm not sure there's anything Scribe can do about that, tbh.

**Comment by dmalmeida** [comment]
Thanks for your answer, shalvah

But is there a way to Scribe send a CSRF token? 
In scribe configuration, there is 'type' 'static' and 'laravel'. If I use 'laravel', isn't there a way to make "post" use a CSRF token?

Sorry my questions. I really am a rookie in laravel and building apis

**Comment by shalvah** [comment]
Out of the box, no. Even if you use type `laravel`, it will simply render the Scribe generated docs, which doesn't include any CSRF token. Your best bet is to [override the Scribe template](https://scribe.knuckles.wtf/laravel/advanced/theming) (seems complex, but all you need to do is create a new theme that's a copy of the existing one) and try to get the [XSRF-TOKEN](https://laravel.com/docs/8.x/csrf#csrf-x-xsrf-token) cookie via JavaScript and add to the request that Try It Out sends. You can send in a PR if you get this to work.

Note that Try It Out currently uses fetch(), not axios, and I'm not sure of how to set defaults for fetch.

Otherwise, you can disable Try It Out.

**Comment by dmalmeida** [comment]
Ok, shalvah

Thanks for your help. For now, I'm leaving this on the side, because I still have some endpoints to finish and my deadline is coming.
I'll disable "Try it out". 
Scribe without "Try it out" is already a great help.
If I have time and succeed to implement it, I'll send a PR.

Thanks again, mate
Cheers

**Comment by shalvah** [comment]
For anyone using Sanctum + CSRF in Try It Out, authentication should work now. See https://github.com/knuckleswtf/scribe/issues/154#issuecomment-916375994
