### ISSUE TITLE
Hosting the static generated documentation

### ISSUE THREAD

**Issue by rmundel** [knuckleswtf/scribe#277]
There's an option to set the path of the included assets?

I'm hosting our documentation in a s3 bucket with a different domain and the index.html is trying to find the assets in **../docs/..**.

```html
    <link rel="stylesheet" href="../docs/css/theme-default.style.css" media="screen">
    <link rel="stylesheet" href="../docs/css/theme-default.print.css" media="print">
    <script src="../docs/js/theme-default-3.6.0.js"></script>

    <link rel="stylesheet"
          href="//unpkg.com/@highlightjs/cdn-assets@10.7.2/styles/obsidian.min.css">
    <script src="//unpkg.com/@highlightjs/cdn-assets@10.7.2/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>
```

**Comment by shalvah** [comment]
Hmm... I'm against adding such a config Atm, because I think it could make things confusing (maybe not for you, but newbies). Would lead to issues like: what's the default? If I change the asset path to x, does it mean the assets will be placed in x, or just the path in the html files that would change? Are relative paths allowed, and relative to where?

Right now, the theme is tightly coupled with the assets, so changing one without the other is weird 

Right now, I think your options are:
1. Use a custom script to do find/replace
2. Publish your own theme, as described in the docs. Basically, you'll need to copy the index file and you can now hardcode your paths.

Also (and this night solve your problem): have you tried changing the `static.output_path`, to a different folder, like `docs/`? Wren you use the default `public/docs`, the asset paths will have `.../docs`; otherwise, they'll just be `./`.

**Comment by rmundel** [comment]
Yeah, chaning to docs/ worked for our use case.
Thanks!
