### ISSUE TITLE
Proposal: Command to create multi documentations.

### ISSUE THREAD

**Issue by yaroslawww** [knuckleswtf/scribe#302]
As I know scribe currently support only one documentation generation. But some medium and big project need supports multiple documentations.

For example web app has multiple provider with different api endpoints and functionality.:

- Some admins: "/api/crm/v1/<endpoints>" - using sanctum or jwt or other token auth
- Partners or advertisers... :  "/api/partners/v1/<endpoints>" - using sanctum or jwt or other token auth
- General users:  "/api/v2/<endpoints>" - using oAuth (passport or any other provider)

If all these routes merge to one documentation - it will be messy and different client developers will be confused.

So my proposal is support multiple documentations with different config files:

Currently we have root config at `<package>/config/scribe.php` then overided by client config `<app>/config/scribe.php`.

and If we add new configuration like  `<app>/config/scribe-crm.php` with custom configsf or `match` and `docs_url`

```php
// <app>/config/scribe-crm.php
return [
    // ...
    'routes'      => [
        [
            // ...
            'match'   => [
                // ...
                'prefixes' => [ 'api/crm/v1*' ],
            ],
        ],
    ],
    // ...
    'static'      => [
        // ...
        'output_path' => 'public/docs/api-crm',
    ],
    // ...
    'laravel'     => [
        // ...
        'docs_url'   => '/docs/api-crm',
    ],
];
```

And then add to generation command new option `config-version` and then based on this option find configuration and override default config.
Quick example:
```
// TODO: add more checks is file exists, etc
if ($this->option('config-version')) {
            // TODO: maybe use deep merge to keep in file only  overridden keys? 
            Config::set('scribe', array_merge(
                Config::get('scribe'),
                require config_path("scribe-{$this->option('config-version')}.php")
            ));
           // --force should be force and --no-extraction false to prevent any future bugs?
            $force        = true;
            $noExtraction = false;
}
```

How do you like this idea? Is there another way to create multiple documents? Or do you think this will be additional functionality that is not needed in the package?

@shalvah

**Comment by shalvah** [comment]
At a point some time back, I did consider bringing support for multiple documentations (by letting you specify an array in the config file), but I decided against it because it introduces too much complexity and confusion for most people.

Your suggestion is better, but I'm still inclined to say no, because of the added complexity for the maintainer, me, for what is a minority use case.

I think this can be done easily in userland, and that's what I suggest you do: you can create your multiple config files and write a wrapper script that renames each config to `scribe.php` and then runs `scribe:generate`. You'll probably also need to rename the `.scribe` folder for each one. 

Alternatively, if you'd prefer an "internal" way, you can extend the `GenerateDocumentation` class, override its logic to handle multiple configs, register that as a new command in your app, and run that instead of Scribe.

**Comment by yaroslawww** [comment]
@shalvah Sure, thank you for feedback.

**Comment by shalvah** [comment]
I just noticed I forgot to mention here: this was later added. https://scribe.knuckles.wtf/laravel/generating#generating-multiple-docs
