### ISSUE TITLE
PHP Content-Type header not displayed in response examples.

### ISSUE THREAD

**Issue by rickdubiel** [knuckleswtf/scribe#330]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

I can't seem to get the PHP Content-Type header to display in any of the response examples. I've also noticed that it's not being displayed in the demo as well for ONLY the PHP language.

https://demo.scribe.knuckles.wtf/

For example it show's up in bash (and javascript, python, and ruby):

![image](https://user-images.githubusercontent.com/18044230/134751180-09de9692-f0fe-495e-a20a-5c231906feee.png)

But not in php:

![image](https://user-images.githubusercontent.com/18044230/134751205-6304a8f0-737c-43b4-90a6-37ddcec53cd4.png)

Thanks!

**Comment by shalvah** [comment]
- Those are request examples, not response examples.
- The content type isn't included, because the Guzzle library, which the PHP examples use, automatically sets it based on the data you provide. For example, passing in `json => [...]` will set it to `application/json`.
- The screenshot you shared is of a GET request, so there's no body **content**;there and hence no content-type, but if you check some other type, you'll see what I mean.
- If you don't agree with this and will prefer to include your headers manually, you can override the language templates with yours. Can't get you the link rn, but it's described in the docs, under Advanced Customisation, I think.

**Comment by rickdubiel** [comment]
> Those are request examples, not response examples.
My bad, I did mean request examples..

> The content type isn't included, because the Guzzle library, which the PHP examples use, automatically sets it based on the data you provide. 
That's interesting, but wouldn't you think we'd still want to display the Content-Type to whoever is integrating the api? Especially for folks like me who wasn't aware that Guzzle did that behind the scenes? I don't know, just feel like it'd be more clear that way.

> The screenshot you shared is of a GET request, so there's no body content;there and hence no content-type, but if you check some other type, you'll see what I mean.
Sorry, bad examples but there is also a POST request on that demo without the Content-Type header as well (even though it's not shown due to bullet #2 above).

![image](https://user-images.githubusercontent.com/18044230/134752710-e5ffa196-1a7f-4426-9e19-3cc36ac3836e.png)

> If you don't agree with this and will prefer to include your headers manually, you can override the language templates with yours. Can't get you the link rn, but it's described in the docs, under Advanced Customisation, I think.
Thank you for pointing this out! This will have to be the route I take. 

Thank you so very much for the quick response! Love the package!
