### ISSUE TITLE
Can you run scribe through controller endpoint? issue with upgrader not being to access config file.

### ISSUE THREAD

**Issue by JohnsAscent** [knuckleswtf/scribe#367]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Im trying to generate docs from a controller endpoint in laravel 8 and while it runs fine when i run the command in console, I am having issues trying to call the command from the controller. When I dug into where the error happened it would be where the upgrader gets called here `$this->upgradeConfigFileIfNeeded();`. When i comment this line out (and i do have the ugraded config) it runs fine with no problems.  It seems to be a problem with the pathing, because the path returned for where the config is, is wrong and i get this error.  

```
"message": "file_get_contents(config/scribe.php): failed to open stream: No such file or directory",
    "exception": "ErrorException",
    "file": "../../../../vendor/shalvah/upgrader/src/ReadsAndWritesAsts.php",
    "line": 36,
```

I have tried a few different workarounds to no avail so i would appreciate any helpful information on how i might resolve this issue.

**Comment by shalvah** [comment]
Not sure why you're calling it from a controller, but you do you.

In this kinds of situations, your workaround is to create your own command. This is where inheritance is useful. You can simply extend Scribe's command and overwrite the `upgradeConfigFileIfNeeded()` to do nothing. Then call your command rather than Scribe's.
