### ISSUE TITLE
Sidebar menu items for headings in intro.md

### ISSUE THREAD

**Issue by sanderbaas** [knuckleswtf/scribe#374]
I am upgrading from version 2 to 3 and everything seems to work fine except the sidebar. In version 2 the h1 and h2 headings from prepend.md were also visible in the sidebar. In version 3 they are not.

How can I get them there without having to edit the templates?

**Comment by shalvah** [comment]
[Correct link here](https://scribe.knuckles.wtf/laravel/migrating-v3#:~:text=For%20the%20%22Introduction%22%20and%20%22Authentication%22%20sections%2C%20Scribe%20still%20uses%20Markdown%20files%20in%20.scribe%2C%20but%20they%20are%20now%20called%20intro.md%20and%20auth.md.%20append.md%20is%20also%20still%20supported%2C%20but%20prepend.md%20has%20been%20dropped.%20If%20you%20were%20using%20a%20prepend.md%2C%20you%20should%20put%20its%20content%20in%20the%20intro.md%20file.).

**Comment by sanderbaas** [comment]
I may not have explained it correctly I am afraid. I put it in intro.md. I have just installed version 3.16.0 and there everything works well. It seems that in version 3.17.0 the sidebar items from intro.md are not generated.

**Comment by shalvah** [comment]
@james2doyle yes, this seems to be happening. I think there's an oversight in your implementation. The sidebar component seems to only load the endpoint headings?

**Comment by james2doyle** [comment]
https://github.com/knuckleswtf/scribe/blob/master/resources/js/theme-default.js#L25

It's grabbing the headings in the `.content`. Should it also be grabbing the headers inside other areas? Or should it be grabbing all header `h` tags?

**Comment by shalvah** [comment]
Yes, it should be grabbing all the h1s and h2s.

**Comment by james2doyle** [comment]
Oh ok, so that's probably why the sidebar was entirely JS and not written with pure blade. It sat there and gobbled up all the header tags and appended them to the sidebar.

With the changes I made, the sidebar is made from the grouped endpoints list (https://github.com/knuckleswtf/scribe/blob/master/resources/views/themes/default/sidebar.blade.php#L25-L42) so it is baked into the HTML output generated by building the docs.

Not sure what the best solution is here for supporting additional headers.

There might be a solution here using the HTML generated list and then some additional items being appended in JS. An HTML-based option might be a list in the config of additional headers/links you want in the sidebar.

If there was a hook or something in the markdown parsing that gave back headers that would be ideal

**Comment by shalvah** [comment]
You could go the markdown parser hook method, but [that might not be easy] (https://stackoverflow.com/questions/25959097/php-parsedown-get-all-headings).

I think it's simpler to just keep the ToC generation in JS. What was wrong with that? We could either switch everything back to JS, or add some JS that loads the other headings apart from the groups and inserts them in the ToC.

**Comment by shalvah** [comment]
@james2doyle since this is broken for everyone, I'll tag a new release at the last known working version. Any chance you can take a look at it sometime later?

**Comment by james2doyle** [comment]
Yeah sorry, kinda slammed. I will try to take a look later. I do wonder if "all headings showing in the sidebar" was more a side effect of the TOC library rather than an actual feature. For anyone without an `intro.md` it is likely the exact same for them as it was before but with the benefits of better performance and a faster/more accurate search.

If you want to rollback to bring this back then please do.

Maybe another option would be to make a 2021 scribe theme that includes these changes, dark mode, as well as the use of prism for highlighting?

**Comment by james2doyle** [comment]
Ok roll it back then. I can take a look at updating the implementation to include those headings but also take a look at a new theme that supports some of the things I mentioned but are also on your list

**Comment by shalvah** [comment]
Made a fix: https://github.com/knuckleswtf/scribe/pull/376. The headings are grabbed when the Markdown is parsed, and sent along to the sidebar component. Very ugly, but it works.

I did notice one bug in the existing implementation, though @james2doyle . Some h1 headings redirect you to the first h2 under them when clicked  (even though the URL shows the hash of the h1). This is bad because there might be content under the h1 that isn't under the h2, and will be missed. Wasn't able to fix it.
