### ISSUE TITLE
PHP Attributes / Object Oriented Documentation??

### ISSUE THREAD

**Issue by jamesaspence** [knuckleswtf/scribe#433]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi there! I'm looking into scribe right now as a potential replacement for https://github.com/vyuldashev/laravel-openapi. This library allows us to define PHP attributes on our endpoints, scan them, and generate openapi docs. Attributes allow us to define documentation consistently (avoiding typos and other things). On top of that, this library allows us to define our documentation for endpoints, responses, etc. in separate factory classes. These classes can be reused, which allows us to define reusable documentation.

Are there any plans to support documentation like this in the future for scribe? It'd be great if we could do something like this in our controllers, as an example:
```php
#[Unauthenticated]
#[QueryParam(name: 'username', required: true, example: 'exampleuser')]
public function getData(Request $request): Response
{
}
```

I also noticed that there were ways to define response JSON, but no similar way to define a complex request body. So it'd be great if, instead of having to define each `@queryParam` and `@bodyParam` separately, we could do something like this instead:
```php
#[QueryParams(factory: GetDataQueryParams::class)]
public function getData(Request $request): Response
{
}
```

and then be able to define a factory class like this (again, as an example):
```php
#[QueryParam(name: 'username', required: true, example: 'exampleuser')]
#[QueryParam(name: 'email', required: true, example: 'foo@email.com')]
class GetDataQueryParams
{
}
```

I realize this is a HUGE feature request, so I'm more wondering if there was any consideration to moving in this direction. I realize it might add a ton of overhead to this project to implement a scanning of the routes that worked like this. Just wondering if there has been any thought or consideration to moving in this direction. Thanks in advance!

**Comment by shalvah** [comment]
I can see the benefit, but there are no plans for this now.

One reason is that Scribe wants to stay out of your production code as much as possible, and attributes are code that still has to be parsed and compiled (minimal cost, maybe, but still a cost). Your controller could easily become cluttered with lots of `use` statements for things that your controller doesn't actually use.

Another reason I'm not really keen on attributes here is that they seem more "authoritative" than comments. But the thing is that Scribe isn't (for now, at least) an API description tool, it's a documentation generator. It's meant to help you get some good docs for your API with reduced effort, not to become *the* canonical representation of your API, because then you'd always be limited by the options Scribe exposes to you.

On the flip side, I can see the benefit: fewer typos, less likely to get stale. But I'm not on this for now. If you wish, you can [create a custom strategy](https://scribe.knuckles.wtf/laravel/advanced/plugins) that uses attributes instead.
