### ISSUE TITLE
`FormRequest::rules` parameters not resolved from container 

### ISSUE THREAD

**Issue by NiclasvanEyk** [knuckleswtf/scribe#459]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
Scribe [extracts `FormRequest::rules`](https://github.com/knuckleswtf/scribe/blob/master/src/Extracting/Strategies/GetFromFormRequestBase.php#L68-L69) using `call_user_func`, but in Laravel, the `rules` method is actually called [using the container](https://github.com/laravel/framework/blob/d1c3d4fb02df18a8b9b31c2ba6e4d76861f33d4b/src/Illuminate/Foundation/Http/FormRequest.php#L113), which injects all necessary dependencies into the function as parameters. When depending on this functionality, scribes generation throws an error at runtime.

instead of...

I would have expected scribe to also use `Container::call`.

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`): 8.1
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version (from `composer show laravel/framework` or `composer show laravel/lumen-framework`): 9.7.0
 - Scribe version (from `composer show knuckleswtf/scribe`): 3.26

**My Scribe config (minus the comments):** 

**Additional info:**

**Comment by shalvah** [comment]
There are fundamental differences between the two.

Laravel uses your form request at runtime. It has an incoming request to pass to it and validate against.

Scribe cannot do that. The GetFromFormRequest strategies aren't trying to validate a request (there isn't any request to validate). Instead, we're trying to hack the form requests and repurpose the validation rules for something else. Going through the container would be slower and not work exactly as you expect, because there's no incoming request.

So we push the responsibility to you, the user. You can use [`instantiateFormRequestUsing()`](https://scribe.knuckles.wtf/laravel/hooks#instantiateformrequestusing). If that doesn't work for you, you can submit a PR to add a more specific hook for that.
