### ISSUE TITLE
How Inline validators + more validation rules  is supposed to work ? 

### ISSUE THREAD

**Issue by virgilekat** [knuckleswtf/scribe#475]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

I'm usigin laravel v8.0 and I have plenty of validators on Controller like : 
`
public function index(Request $request)
	{
		$this->validate($request, [
			'my_parameter' => 'filled|boolean'
		]);
`

but scribe doesn't generate anything 

I've tried to write it like it is in the documentation : 

`
public function index(Request $request)
	{
		$request->validate( [
			'my_parameter' => 'filled|boolean'
		]);
`

But it didn't worked either ... 

Am I missing something  ?? 

Thanks

**Comment by leandrodiogenes** [comment]
Scribe does not interpret validations made inside methods.
The ideal is to make a docblock or a formRequest
See parameters section on documentation.
[https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters](url)

**Comment by keatliang2005** [comment]
From the V3 documentation this supposed to work, instead it generates without body parameters
https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#validation-rules

**Comment by shalvah** [comment]
Yes, Scribe supports inline validators. It should capture that. At this point, you need to do some debugging. Go into `lookForInlineValidationRules` in `GetFromInlineValidatorBase`, where Scribe is trying to parse the text of your code, and dump some of the intermediate values and let me know what Scribe is seeing.

**Comment by keatliang2005** [comment]
after peak in the Class suggested i know what scribe look for

```php
$validated = $request->validate(...) // this work

$request->validate(...) // this does not
```

it's very specific, maybe the documentation can update with more clear about this.

also the method `lookForInlineValidationRules` only look for first 6 statements in the method,
if the validation statement further then 6 statements it wont work either.

Suggestion: maybe have a option to follow controller method statement and also dive into function call in the statement in order to further drill down to look for validation rule, and that can be configure with a config value

**Comment by shalvah** [comment]
Alright. Will change it later so that it doesn't need `$validated =` to work.

The 6 line limit is because validation usually happens early on, so there's no reason to keep checking. Maybe I'll take it up to 10.

> have a option to follow controller method statement and also dive into function call in the statement in order to further drill down to look for validation rule

I don't know if I'll do this. Right now, we're only parsing the controller file. Function calls could be to other functions in the same class, or to another class or global function., meaning we'd need to parse your whole codebase. So not likely.

**Comment by virgilekat** [comment]
Hi all sorry for the delay, I was off. 

Indeed 

`$validated = $request->validate(...) `

Works for me. 

Indeed could be great to have that info on V3 documentation. 

Would be better to have it handled with just : 
`$request->validate(...)`

At the same time, there is a third writing that could be handled : 

`$this->validate($request, `

Thanks a lot !

**Comment by shalvah** [comment]
`$request->validate(...)`and `$this->validate($request, ...)` are supported now (3.30.1).

https://github.com/knuckleswtf/scribe/blob/29940c2e05c8035a1ab85d9482c2335e1747ab41/src/Extracting/Strategies/GetFromInlineValidatorBase.php#L139-L144
