### ISSUE TITLE
How to create Sub Groups with the documentation?

### ISSUE THREAD

**Issue by harisch470** [knuckleswtf/scribe#484]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.
 How can I achieve creating the sub or nested groups like the following?
 
```
@group User Management:
      @group Profile Management
      @group Authentication Management
```

**Comment by leandrodiogenes** [comment]
Hi @harisch470 , i dont think is possible at moment.

**Comment by shalvah** [comment]
I see this has been requested a couple of times (see also #403 and #483. I can see the usefulness, but it's not easy. A lot of Scribe's architecture is based on the group thing, and adding sub-groups to the mix would be difficult to get right while keeping features like group and endpoint sorting, editing Camel files. It would also need major UI changes, and because of the complexity involved, would likely also introduce subtle bugs.

I'll investigate this sometime this month or next, as part of plans for Scribe v4, but no promises yet. I may end up just making the `subgroup` thing not really a group, but an extra metadata field with some limited functionality.

**Comment by shalvah** [comment]
Subgroup support implemented and coming in v4 ✅ 



![Image](https://user-images.githubusercontent.com/14361073/178120950-5878fae7-603d-4df1-9cd1-d259f3788436.png)

**Comment by shalvah** [comment]
v4 released!
