### ISSUE TITLE
RTL Supprort

### ISSUE THREAD

**Issue by neomn** [knuckleswtf/scribe#498]
- [ ] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

does scribe support right-to-left languages?

**Comment by shalvah** [comment]
There's no specific support for RTL languages, but there's no guarantee they won't work either. However, the parsing of docblocks is text-dependent, so probably won't work with RTL, and some of the UI styling probably assumes an LTR language. (In the next major, we'll introduce PHP 8 Attributes, so those can be used instead of docblocks.)

Unfortunately, there are no plans for better support any time soon.
