### ISSUE TITLE
JWT authorization

### ISSUE THREAD

**Issue by antizhyk** [knuckleswtf/scribe#500]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Good afternoon, my application uses JWT authorization. In the generated documentation from "srcibe" authorization is possible, but I can't figure out if after authorization I can take the "access_token" from the request and put it in the repository to use this token in the Authorization Bearer headers. Is it possible in principle? 
I found that you can add token in scribe.php configuration or with beforeResponseCall() hook, but as I saw it, this means adding token manually. And I need exactly what I can authorize in documentation (add token) and exit (delete token) and then authorize again (and new token is added to repository).

**Comment by shalvah** [comment]
I'm a bit confused. Do you mean that you want to use the

**Comment by antizhyk** [comment]
I apologize for not answering for a long time. I need to make the documentation so that after authorization, the received token is substituted in the header to other requests from the documentation.

**Comment by shalvah** [comment]
Still not sure what you mean....

Do you mean in the Try It Out feature (ie a user can test the authorize endpoint then use that for other endpoints)? No, no easy way.  But as long as you provide auth instructions, the user should be able to follow that manually.

Otherwise, if you're talking about Scribe dynamically fetching a token during generation and then showing that in the examples, that isn't supported officially, too. But there are ways to make it work. I recommmend just using a specific token for the documentation.

**Comment by antizhyk** [comment]
Great, just what I needed, thanks for helping me out with my question.
