### ISSUE TITLE
base_url not updating

### ISSUE THREAD

**Issue by oliverbj** [knuckleswtf/scribe#512]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.knuckles.wtf/laravel/troubleshooting).**

**What happened?**
1. I changed the `base_url` setting in the config file to another value such as: https://example.org
2. Then I ran `php artisan scribe:generate` ...
3. But the `base_url` mentioned in the docs is not updated - it still shows `http://localhost`

**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`): : 8.1.9
 - Framework (Laravel/Lumen): Laravel 9.25.1
 - Scribe version (from `composer show knuckleswtf/scribe`): versions : * 3.36.0

**My Scribe config (minus the comments):**

```php
'base_url' => 'https://example.org',
```

**Comment by dev-telescopic** [comment]
Hi there, I'm experiencing the same problem

PHP 8.2.4
Laravel 10.4.1
Scribe ^4.17

My config file uses a custom.test url

The example requests in the documentation looks ok, eg

Example request:
curl --request POST \
    "http://custom.test/api/register" \


However, when I click on make request, I get an error because the page is invoking localhost?

I checked the index.html file generated after I run  "php artisan scribe:generate" and it's showing localhost in the baseUrl?

    <script>
        var baseUrl = "http://localhost";
        var useCsrf = Boolean();
        var csrfUrl = "/sanctum/csrf-cookie";
    </script>

**Comment by ObsidianBlaze** [comment]
I experienced the same issue when hosting a website on LaravelCloud using Scribe. It always goes back to using localhost.
I resolved it by ensuring that the index.php file had the baseUrl of the live server.
When I eventually ran the command locally, everything worked well on both the server and localhost.
