### ISSUE TITLE
Save to run in production

### ISSUE THREAD

**Issue by rv-aholsinger** [knuckleswtf/scribe#530]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Hi.. I noticed that your instructions ask to install scribe as a dev dependency. However it is preferable that we have the docs available in prod. Are there any known security issues with this? I thought perhaps that might be the reason to install it as a dev dependency.

**Comment by leandrodiogenes** [comment]
Hi @rv-aholsinger .
I don't think it has any library-related security dangers.
But i really don't recommend to do that.
Your biggest risk will be exposing sensitive data when generating documentation in a production database.
Scribe uses the database to generate example responses.

**Comment by shalvah** [comment]
There aren't any known security issues. We recommend installing as dev because there's no need installing extra packages that you don't need to handle your users' requests.

So it's fine to install in production, but as @leandrodiogenes says, you should be careful.
- Response calls (only GETs by default) will call your app, which might talk to a database or external services.
- API resource responses will try to fetch a model from your database
- FormRequest rules() will be executed, although they are not executed within a full Laravel context, so might not have much effect.

You could disable all of these if you aren't sure if your footing. I'd also recommend using [a custom environment](https://scribe.knuckles.wtf/laravel/tasks/generating#customising-the-environment) where you configure a database and double-checking to be sure you've disabled any unwanted external service calls.

**Comment by rv-aholsinger** [comment]
Ok.. that makes sense. Yeah I have all of the functionality to actually call the APIs turned off.   Also I have a middleware to only show the docs on network. Thanks for your perspective.
