### ISSUE TITLE
Single controller for PUT and POST ?

### ISSUE THREAD

**Issue by vool** [knuckleswtf/scribe#531]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

This is similar to [issue 176](https://github.com/knuckleswtf/scribe/issues/176) but what I expect is much less of an edge case 

I have a controller method which can be requested by a PUT and POST,  both have the same fields (so the same docs work) but the PUT also has the record ID as a required field 

```
Route::post('api/foo', 'FooController@save');
Route::put('api/foo', 'FooController@save');
```

Is there someway that two records in the documentation can be achieved without adding the endpoints manually ?

**Comment by shalvah** [comment]
Hmm. No direct support for this now, and I'm not yet sure this is a use case we want to support.

There are ways you can achieve this, of course.
1. You could write custom strategies, but that would probably require you overwriting several strategies, since they all handle only one part of the extraction.

2. You could edit the generated YAML files, and Scribe will respect your changes (unless you use `--force`)

3. You could subclass the `Extractor` and add some custom logic for these endpoints, similar to the existing one for inherited methods:

https://github.com/knuckleswtf/scribe/blob/5be39d6d97b1823821173182f41643f91f1b4d21/src/Extracting/Extractor.php#L53-L59


For the subclass approach to work, you'd need to also subclass `GroupedEndpointsFromApp` to return your custom Extractor:

https://github.com/knuckleswtf/scribe/blob/527fdc2067a091d388ff26637bc5edf23e222d2c/src/GroupedEndpoints/GroupedEndpointsFromApp.php#L255-L288

_and_ then subclass `GroupedEndpointsFactory` to return your custom `GroupedEndpointsFromApp`:

https://github.com/knuckleswtf/scribe/blob/5a87b418d483a95ae4ed74dba63987f72c436d9b/src/GroupedEndpoints/GroupedEndpointsFactory.php#L23-L30

_and_ then register that in the service container so that laravel passes it to the [`GenerateDocumentation` command](https://github.com/knuckleswtf/scribe/blob/527fdc2067a091d388ff26637bc5edf23e222d2c/src/Commands/GenerateDocumentation.php#L41)

```php
app()->when(GenerateDocumentation::class)
          ->needs(GroupedEndpointsFactory::class)
          ->give(fn() => new CustomGroupedEndpointsFactory);
```

Option 3 seems complicated, but luckily your subclasses just need to change one line in the class. Option 2 seems easiest, but might be more flaky. Alternately, we could add an `afterExtracting()` [hook](https://scribe.knuckles.wtf/laravel/hooks), but I'm not yet convinced it's a need. What do you think?
