### ISSUE TITLE
When using an enum in a route an extra url parameter is created

### ISSUE THREAD

**Issue by rdsurf** [knuckleswtf/scribe#565]
When I use an enum in a route as an url parameter, it lists 3 instead of 2 url parameters.

If I have the following route `/account/{account}/status/{status}` where in status is an enum. I get the following url parameters:

- account_id
- id
- status

I'd expect to get 2 url parameters, or is this intended behavior? If so, how can I get rid of one? I tried to overwrite the yaml files in the `.scribe` folder. But this overwrites my changes after subsequent calls.

**Comment by shalvah** [comment]
I wasn't able to reproduce this.

![image](https://user-images.githubusercontent.com/14361073/204041944-6681bfa5-716a-4e73-9219-ea5e63315e9c.png)

![image](https://user-images.githubusercontent.com/14361073/204042016-06b0bdc1-4d56-40ec-874e-d3f6a434dc6e.png)


Please always include your package version and configuration details. It's very annoying to waste my time like this. That's why there's a template.
