### ISSUE TITLE
Error after trying to try any endpoint from /docs

### ISSUE THREAD

**Issue by kusem** [knuckleswtf/scribe#569]
- [x] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

First of all, thank you for this incredible and easy-to-use plugin!

I've faced an issue - all docs are generating, and some examples are loading well (as well as Scribe reaches endpoints) - but ANY "Try it out" button on the page doesn't work - throws an error **_"window.hljs.highlightElement is not a function"_**. To be honest, I just can't find out why. 
Laravel 9, latest Scribe.

Thank you in advance.

**Comment by shalvah** [comment]
Hm, I can't reproduce that. That is a frontend JavaScript error, It sounds like there's something weird with your setup. Try doing a hard-refresh. Or take a look at your browser dev tools, and see if the highlightJS script is being loaded. Also—are you running Larave Debug Bar? I've heard it can cause issues because it's using a different version of highlightJS.

**Comment by kusem** [comment]
> Hm, I can't reproduce that. That is a frontend JavaScript error, It sounds like there's something weird with your setup. Try doing a hard-refresh. Or take a look at your browser dev tools, and see if the highlightJS script is being loaded. Also—are you running Larave Debug Bar? I've heard it can cause issues because it's using a different version of highlightJS.

**Thank you**, the problem really was in the debugbar. 
Just for information on how to solve it - you'd exclude the docs directory in debug config so it doesn't launch there.

**Comment by shalvah** [comment]
👍 

It's in the docs now. https://scribe.knuckles.wtf/laravel/troubleshooting#typeerror-hljshighlightelement--hljshighlightall-is-not-a-function
