### ISSUE TITLE
Stuck on PHP 7.4

### ISSUE THREAD

**Issue by bakiro** [knuckleswtf/scribe#59]
Hi Shalva!, the command php artisan scribe:generate is stuck when has php 7.4 version,

Thanks for you work!

**Comment by shalvah** [comment]
100% sure it works on PHP 7.4. My development machine is 7.4.

This isn't how to log an issue. You're meant to do some investigating so that you can provide useful information to the library maintained. That's why there's an issue template (which you didn't use) that guides you in including important details. The language version is helpful, but that doesn't tell me anything about your setup, what you did, or where you're stuck. I'm closing this issue until you can provide more useful information.
