### ISSUE TITLE
security

### ISSUE THREAD

**Issue by demobiel** [knuckleswtf/scribe#619]
!!IMPORTANT!!

READ BEFORE OPENING AN ISSUE:

- If you don't provide enough information in your issue for me to reproduce (such as version and any custom configuration), I will close it. I can't keep wasting my time investigating issues which no longer exist.
- Check the Troubleshooting Guide! https://scribe.knuckles.wtf/laravel/troubleshooting Some solutions to common problems are detailed there.

- [X ] I've read the [documentation](https://scribe.knuckles.wtf/laravel) and I can't find details on how to achieve this.

Okay, but DID YOU REALLY CHECK THE DOCS? Use the search bar on the docs page, and then come back and put an x in the box above only if you don't find answers. I know it's difficult when you don't know what you're looking for, but do your best.

Why are the authorization schemes and @authenticated not added as "security" attribute for the paths, but directly into the "header" or "query"?

Would it be possible to support multiple authorization schemes?

Is this something wanted? if yes, I am willing to contribute!

**Comment by shalvah** [comment]
> Would it be possible to support multiple authorization schemes?

I'd say pretty unlikely, as this use case meets the needs of most APIs. Also, the `openapi.yaml` is not Scribe's primary focus, but rather the human-readable documentation.

I'll close this because like I said, it's pretty unlikely. However, I'll consider it if you can present an implementation that won't make using Scribe more complicated for the majority use case.
