### ISSUE TITLE
Feature Request: Add automatic detection of Laravel validators

### ISSUE THREAD

**Issue by bigbenbeer** [knuckleswtf/scribe#65]
### Scenario
I have a JSON API which allows an external user to POST lots of data to my server. All the incoming data I validate using the [Laravel Validator](https://laravel.com/docs/7.x/validation). An example of my controller's contents is as follows:

```
$validator = Validator::make(
    $postbody,
        [
            'parameter1'  => ['required', 'numeric', ...],
            'parameter2'  => ['required', 'numeric', ...],
        ]
    );
    if ($validator->fails()) {
        return response()->json($validator->errors(), 400);
    } else {
        //Validation passed
    }

```
These parameters are currently documented as follows:
```
/**
 * @group Endpoint Group
 * 
 * Some Title
 * @bodyParam parameter1 number required Some kind of description. Example: 12356
 * @bodyParam parameter2 number required Some kind of description. Example: 12356
 */
```
### Feature Request
Please add automatic detection of these Validator rules so that body parameters do not need to be manually specified. The user can then enter manual descriptions via the `@bodyParam` should they wish to do so otherwise the auto-generated validation rules can be used instead.

**Comment by shalvah** [comment]
That would indeed be a nice feature. Unfortunately, I've considered this in depth several months ago, and it turns out there are so many technical limitations that make this unfeasible.

Let's say we want to do this. There are two ways of retrieving the validation rules:

## Hooking into Laravel's validator and executing the controller method so the validation can run
This can be problematic in so many ways (side effects and the like). The code in your controller isn't only validation-related. Sure, ideally, your environment setting should nullify these, but we often forget. Imagine sending out a bunch of emails (or worse) just because you were trying to document your APIs.

## Manually reading the file and parsing the code
This seems like a better approach, but there are so many different variables that complicate things.
- First, there's the different possible validation syntaxes. And then there's the different ways people write PHP. and Laravel. Some people extract the rules into a separate variable first. Oh, and then there's the fact that some people extract theirs into a separate function. All of those don't sound very complex, but when you're reading a source code file programmatically, it quickly becomes a mess when you try to handle more than the basics.
- Then there's the problem that we can't evaluate variables and dependencies, so for a rule like `"in:$allowedValues"`, we'd have to go back and figure out what `$allowedValues` are. For a simple variable declaration, it would be fine, but what if it's the result of a function call? That would complicate things massively. And you have things like `"in:".Auth::id()` too.

At the very minimum, we'd likely need to actually parse the code and create an AST rather than try to parse the actual lines. But I don't know how easy it would be to figure out the validation rules from the AST as well.

Note that FormRequests are supported because they present less of a challenge: the logic within the rules() method is often exclusively validation-related and self-contained,

If you have suggestions on working around these, I'm game. I might also look into alternatives once more, but no timeline. An alternative I considered briefly is a response call with a hooked validator that always fails (so code execution halts), but that's still dicey.

**Comment by bigbenbeer** [comment]
Gosh I hadn't even considered all of that. I suppose one workaround would be a _dictative_ solution whereby Scribe specifically specifies the format/syntax to be used for Validator methods if auto-doc generation is something a developer wants. Then you can limit the scope of the solution and prevent catering for endless possibilities. Then it becomes a more narrowed problem: "Is a specified Validator syntax present, yes ok lets auto-generate the docs, no, lets revert back to manual and create a command-line warning for the user".

Anyways, just my ideas.

**Comment by shalvah** [comment]
Yes, I can't see any solution that doesn't involve limiting the scope. Even FormRequest support—it was removed back in the day because there were too many problems. Only added it back when I decided to restrict the possibilities.

I'll look into this when I have time, maybe do a proof of concept. I'm for as much automation as possible. It's an interesting challenge. No guarantees, though.

In the meantime, if you've got any other general feedback on Scribe, could you share in this [feedback thread](https://github.com/knuckleswtf/scribe/issues/66)? Also pass on the link to anyone you know who uses it.🙏

**Comment by shalvah** [comment]
Good news: this is coming in v3! It's taken a while, but I've implemented this, and it currently works with `$request->validate` and `Validator::make`. It's still experimental, so it's a bit limited—only supports plain string/array rules (no expressions like `"in:".join(",", [1, 2, 3])` supported). But yeah, it works, and you can add comments with description and example like this:


```
$validated = $request->validate([
  // Description of param1. Example: thing
  'param1' => '...
```

**Comment by bigbenbeer** [comment]
Awesome, I will check it out!

**Comment by shalvah** [comment]
🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3)!

**Comment by michaelandrew123** [comment]
Hi anyone can tell me how to fix the issue? 

How to send a valid json string to validator json?
I use this command "@queryParam customer_ids string[] required"
Thanks in advance. 

![image](https://user-images.githubusercontent.com/74481170/171202123-9cf0c3ff-9c5c-497b-9b47-405ae677d3b1.png)

**Comment by michaelandrew123** [comment]
> 🎉[v3 is out now](https://scribe.knuckles.wtf/blog/2021/06/08/laravel-v3)!

Can you tell about my post? I have an issue fixing the error. Thanks.
