### ISSUE TITLE
Regex in annotations make trouble generating example requests

### ISSUE THREAD

**Issue by stell** [knuckleswtf/scribe#68]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.

I have two example routes, which have some regex to specify allowed values:

```
 $router->get('objects/{locale:[A-Z]{2}}',  ['uses' => 'ObjectController@showLocaleObjects']);
 $router->get('objects/{id:[0-9]+}',  ['uses' => 'ObjectController@showObject']);
```

The API works fine, but the docs are not getting generated with correct example values.

One of the controller functions:

```
public function showLocaleObjects($locale, Request $request)
{
    return response()->json(Object::where('locale', 'LIKE', '%' . $locale . '%')->get());
}
```

The annotations:

```
/**
* GET locale objects
* 
* This endpoint gets specified locale objects.
* 
* @urlParam locale required ISO 3166-1-alpha-2 code. Example: FR
* 
*/
```
With regex: http://localhost/api/v1/objects/1
Without regex:  http://localhost/api/v1/objects/FR (like specified in the Example)

Am i missing something?

**Comment by shalvah** [comment]
Interesting. Sounds like a bug in the implementation. Shouldn't be too hard to investigate this (look for where examples are generated in the relevant strategy and check out what's going on there), but I won't have time for a while, so any contribution is welcome.

**Comment by shalvah** [comment]
Fixed in 1.8.2

**Comment by shalvah** [comment]
Welp, reverting this change because it broke something. Also, you didn't let me know that this is Dingo router (figured that out because Laravel doesn't support this syntax, even though I couldn't find any mention in the Dingo docs).

I'm closing this issue as a wontfix. I don't think there's much value in adding this.

**Comment by stell** [comment]
Dingo Router? Not used. It's native Lumen.

**Comment by shalvah** [comment]
I see. You shoulda mentioned that.

**Comment by shalvah** [comment]
This is why there's a bug report template^^^

**Comment by shalvah** [comment]
Fixed this in the upcoming v2 - https://github.com/knuckleswtf/scribe/commit/53208d93858b8d7fb8b5e5e67f79362811e632b5. Did a few rough tests on my machine, but not more than that, because setting up automated tests for this with Lumen is a Herculean tash.

Seriously, people need to stop using Lumen.😐
