### ISSUE TITLE
RouteMatcher config option ignored

### ISSUE THREAD

**Issue by Floppy012** [knuckleswtf/scribe#745]
### Scribe version

4.25.0

### PHP version

8.2.9

### Framework

Laravel

### Framework version

10.26.2

### Scribe config

```ruby
routeMatcher => "App\\Docs\\CustomRouteMatcher"
```

### What happened?

When generating docs, the custom route matcher is not called. I am using a custom configuration file `scribe-v1` with the `--config` option when generating. Generating itself works fine but its not using my custom route matcher. I've tried to find where that config option is being read but couldn't find anything.

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
It's used here:

https://github.com/knuckleswtf/scribe/blob/46b5a2562184ba64002ecc744b54a2f5d2d9d3bf/src/ScribeServiceProvider.php#L33

I think it doesn't work because it's looking for `scribe` (so it doesn't support custom config).

I don't really like that config option anyway. Will probably remove it in future. I'm thinking, maybe it's better to just bind your preferred object yourself? Something like:

```php
$this->app->bind(RouteMatcherInterface::class, RouteMatcher::class)
```

Although you have to ensure it's in a service provider loaded after Scribe's (or use contextual binding: `when(GenerateDocumentation)->needs(...)->give(...)`).
