### ISSUE TITLE
When using FormRequest with 'file' validation, request data is empty even data is provided in docs example body

### ISSUE THREAD

**Issue by lHondol** [knuckleswtf/scribe#764]
### Scribe version

4.23

### PHP version

8.2.4

### Framework

Laravel

### Framework version

10

### Scribe config

```ruby
theme => "elements"
title => "Notex"                  
base_url => "http://localhost:8000"           
try_it_out.base_url => "http://localhost:8000"
auth.enabled => true
auth.default => true
auth.name => "Authorization"
```

### What happened?

In my FormRequest, i have these rules:

    public function rules(): array
    {
        return [
            'information' => ['required'],
            'file' => ['required', 'file'],
        ];
    }

In the generated documentation, within the "try_out" body, I can now choose the file I need to upload. However, when I hit submit, the response states, 'The information field is required,' even though I have already provided the value.

also the request payload:
```
------WebKitFormBoundaryPuRQG2gkhYZdgo8K
Content-Disposition: form-data; name="information"


tempore

------WebKitFormBoundaryPuRQG2gkhYZdgo8K
Content-Disposition: form-data; name="file"; filename="myfile.pdf"
Content-Type: application/pdf


------WebKitFormBoundaryPuRQG2gkhYZdgo8K--
```

request headers :
Content-Type: 'multipart/form-data'
Accept: 'application/json'[](url)

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by mcpicoli** [comment]
Having similar trouble here using try-it-out. Route uses HTTP PUT method and has a "file" parameter named "photo". ```php artisan scribe:generate``` generates "correct" documentation, I can pick a file and fill other parameters. If no file is selected, everything works fine, only when providing it, it is missing as described by the OP.

#257 should have fixed this problem, but the HTTP method is never changed to POST, the hidden parameter "_method" is never added and the Content-Type header is never changed to multipart/form-data. The file is never seen by the server (as expected since PUT does not support multipart/form-data in PHP) and because of that the validation logic fails, stating the file is invalid since it is encoded as an empty JSON body.

```{"photo":{}}```

The request header, as per the browser developer tools is not changed from "Content-Type: application/json"

If I change the header manually to "multipart/form-data", the validation logic passes (the file is not mandatory), but the try-it-out does not send anything multipart encoded (file is missing), nothing is done at all regarding the file. The correct (manually changed) Content-Type is sent, but (if I am not understanding something wrong), it should be deleted (line 192)

**Comment by shalvah** [comment]
Thanks for your preliminary investigation. I'll look at this some more when I have the time, but in the meantime, feel free to submit a PR if you have an idea what needs to be fixed.

**Comment by wlhrtr** [comment]
When uploading a file the `Content-Type` header must not be set otherwise the browser cannot set the right boundaries for the multipart formdata payload.

<img width="804" alt="Bildschirmfoto 2024-06-06 um 12 07 56" src="https://github.com/knuckleswtf/scribe/assets/7114260/293dd67c-4055-4fd3-9229-241bd48c1cf6">

You can add following code to `index.blade.php` of vendor published elements template in line `:126` to get it to work

``` javascript 
// ...
let preflightPromise = Promise.resolve();
if (window.useCsrf && window.csrfUrl) {
    preflightPromise = makeAPICall('GET', window.csrfUrl).then(() => {
        headers['X-XSRF-TOKEN'] = getCookie('XSRF-TOKEN');
    });
}

// START this needs to be added
if (form.dataset.hasfiles === "1") {
    delete headers['Content-Type'];
}
// END this needs to be added

return preflightPromise.then(() => makeAPICall(method, path, body, query, headers, endpointId))
// ...
```

**Comment by shalvah** [comment]
Can you make a PR with that fix?
