### ISSUE TITLE
api requires authentication not working 

### ISSUE THREAD

**Issue by neppoz** [knuckleswtf/scribe#81]
- [x] I've read the [documentation](https://scribe.rtfd.io) and I can't find details on how to achieve this.
Hi,

i tried in various ways to document the api where authentication is required. I have a bearer token for my application and i can use Postman to access the api like a charm.

It seems that the auth settings in config are not working. Using verbose flag for error reporting, but no output regarding authentication. Someone use the package with a api that requires authentication and can help?

**Comment by shalvah** [comment]
The good news is that authentication definitely works.🙂 I'm almost certain that you're missing something.

If you'd like help with solving your issue, you'll need to provide more information. Primarily the details requested in the issue template for bug report.

**Comment by neppoz** [comment]
I am also sure that i am missing something. Maybe someone can help me out with this

**What happened?**
1. I set my configuration to use authentication. My API is protected with auth:sanctum in the middleware and i set a personal_access_token. The access with postman is working as expected
2. Then I ran `php artisan scribe:generate`, the documents are generated and i can access the docs.
3. But in the docs example response shows
`{
    "message": "Unauthenticated."
}`

instead of displaying the response data.


**Screenshots and stack traces:**

**My environment:**
 - PHP version (from `php -v`): 7.4.7
 - Framework (Laravel/Lumen):  Laravel v7.16.1
 - Scribe version (from `composer show knuckleswtf/scribe`): 1.3.3

**My Scribe config (minus the comments):**
`<?php

return [
    'type' => 'laravel',
    'static' => [
        'output_path' => 'public/docs',
    ],

    'laravel' => [

        'add_routes' => true,
        'docs_url' => '/docs',
        'middleware' => ['auth'],
    ],
    'auth' => [
        'enabled' => true,
        'in' => 'bearer',
        'name' => 'token',
        'use_value' => env('SCRIBE_AUTH_KEY'), **--> this is set in env**
    ],`

**Comment by shalvah** [comment]
> But in the docs example response shows
{ "message": "Unauthenticated." }

Okay, this means that your issue is with response calls, not auth documentation itself. You'll need to debug this yourself:
- verify that SCRIBE_AUTH_KEY is actually being read. One way is by adding a `dd(env('SCRIBE_AUTH_KEY'))` at the top of the config file (before the return).
- verify what is being sent in the request. Probably dump the request headers in your auth middleware

**Comment by robtesch** [comment]
Hi @shalvah I've just hit a similar problem and I realise now what's happening, but can't quite figure out a non-hacky way of fixing it.

I run the ``scribe:generate`` command on my local machine, which obviously has a different URL to my production environment, but in order to have the correct urls show up in production documentation, I have to set ``base_url`` to my production URL.

This was previously a problem because actually, I have multiple production environments, so I have to just put my "most popular" ``base_url`` in there, and it's not personalised to each individual instance, however it seemed to work fine.

Despite setting that ``base_url`` to my production url, scribe was still smart enough to use my local url as the one to actually make API requests to when it came to automatically generating response documentation (or at least, I'm quite sure it did, because I'm sure this was working before).

Now it seems a recent update has caused scribe to actually try using that ``base_url`` instead of my local url, thereby causing the ``Unauthenticated.`` responses (because of course I am not using an API key from production, but from local).

So, I'm not too sure how best to solve this one, because I imagine the current behaviour would be desired by a lot of people, perhaps they run scribe:generate during deploy or something? In my case this is not possible because I have to make some minor manual adjustments to the output every time (CSP Nonce for script tags in generated documentation).

A couple of possible suggestions:

1) Use ``base_url`` only for the generated documentation, and not for scribe making the api calls.
2) Use ``base_url`` only for the generate postman collection, and use ``{{ config('app.env') }}`` in generated docs. This would have the benefit of being largely personalised in different production environments, but would mean the postman collection etc would potentially be different to the docs.
3) Introduce yet another config value, something like ``response_call_url`` or ``use_local_for_responses``. That way we could do the response calls to one place, but optionally have a different "production" url in the generated docs.
3) Tell me nothing can be done, and then I will just do a hacky "find/replace" on generated docs, but use my local url as the ``base_url`` setting.

**Comment by robtesch** [comment]
Update - finally realised what the issue is. I added a bunch of new routes to the docs, and didn't add the ``@authenticated`` doc block to them.

@shalvah is there a setting somewhere we could set to say that ALL the API routes require auth?

**Comment by shalvah** [comment]
Ah, lol. For what it's worth, the JS version uses a separate `responseCalls.baseUrl` (https://github.com/knuckleswtf/scribe-js/blob/master/config.js#L87), but that's because the response call mechanism actually makes an external request. Glad to see that it's working as expected here.

> is there a setting somewhere we could set to say that ALL the API routes require auth?

Hmm. Probably will change the behaviour of `auth.enabled` in v2.

> finally realised what the issue is. I added a bunch of new routes to the docs, and didn't add the @authenticated doc block to them.

@neppoz you should check if this is your problem too

**Comment by shalvah** [comment]
In the meantime @robtesch it's easy to write a custom strategy that sets all your endpoints to authenticate. See https://scribe.readthedocs.io/en/latest/plugins.html

**Comment by robtesch** [comment]
> In the meantime @robtesch it's easy to write a custom strategy that sets all your endpoints to authenticate. See https://scribe.readthedocs.io/en/latest/plugins.html

Yeah, i did look into that before but for reason it didn't quite "click" in my mind, and I had some other pressing things to do.

Either way, I am going to have to add some more documentation to all these new endpoints (well, new to the API docs anyway), so I may as well add the ``@authenticate`` tag, no biggie.

**Comment by neppoz** [comment]
> > But in the docs example response shows
> > { "message": "Unauthenticated." }
> 
> Okay, this means that your issue is with response calls, not auth documentation itself. You'll need to debug this some more:
> 
> * verify that SCRIBE_AUTH_KEY is actually being read. One way is by adding a `dd(env('SCRIBE_AUTH_KEY'))` at the top of the config file (before the return).
> * verify what is being sent in the request. Probably dump the request headers in your auth middleware

The missing @authenticate in docblock was the problem. You can close this issue. It was a configuration error. Thank you for your support!

Thanks to @shalvah what pointed me in the right direction.

**Comment by HamxaJ** [comment]
I wanted to add two fields in auth like (bearer and x-api-key)
'auth' => [
    'enabled' => true,
    'in' => 'bearer', // here I wante that my doc will show two fields for beare token and x-api-key
    'name' => 'token',
    'use_value' => env('SCRIBE_AUTH_KEY'), **--> this is set in env**
],`
someone guide me if there is any way to add it
