### ISSUE TITLE
Bugs with custom rules.

### ISSUE THREAD

**Issue by dvlpr91** [knuckleswtf/scribe#913]
### Scribe version

4.38.0

### PHP version

8.3.4

### Framework

Laravel

### Framework version

11.30.0

### Scribe config

```ruby
type => "laravel"
theme => "elements"
laravel.assets_directory => "vendor/scribe"
laravel.middleware.0 => "App\\Http\\Middleware\\OnlyLocalEnvironment"
try_it_out.csrf_url => "/csrf-cookie"
auth.enabled => true
auth.name => "Authorization"
auth.placeholder => "{token}"
postman.enabled => false
openapi.enabled => false
strategies.headers => added [
    'override',
    [
        'Accept' => 'application/json',
    ],
]: removed [
    'override',
    [
        'Content-Type' => 'application/json',
        'Accept' => 'application/json',
    ],
]
strategies.responses => added [
    'Knuckles\\Scribe\\Extracting\\Strategies\\Responses\\ResponseCalls',
    [
        'only' => [
            'GET *',
        ],
    ],
]: removed [
    'Knuckles\\Scribe\\Extracting\\Strategies\\Responses\\ResponseCalls',
    [
        'only' => [
            'GET *',
        ],
        'config' => [
            'app.debug' => false,
        ],
    ],
]
```

### What happened?

hello.

I have created a custom rule.

And when I code it to be called from a separate FormRequest, and generate a document, utilizing the docs() method of the custom rule, I see normal results (description, example data, etc.).

However, when I call the custom rule directly from the controller, the rules in the custom rule work, but I don't get the descriptions, example data, etc. that I defined in the docs() method. (It seems that it just doesn't call the docs() method).

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by dvlpr91** [comment]
After checking, there is a big difference in how the rules are fetched from the `GetFromInlineValidatorBase` file and the `GetFromFormRequestBase` file.

This is unlikely to be easy to improve in the short term.

**Comment by dvlpr91** [comment]
Oh... As it turns out, this works with the same mechanism not only for custom rules, but also for any call to a static method of the rule class when calling the rule as an array (rather than a string) from the controller.

Is this not a bug, but an unimplemented feature?

**Comment by shalvah** [comment]
> there is a big difference in how the rules are fetched from the GetFromInlineValidatorBase file and the GetFromFormRequestBase file.

Yes, this is by design. They are two different mechanisms which evolved separately and have different limitations.
- `GetFromFormRequestBase`, the older approach, instantiates the Form Request using Laravel. However, there is no real HTTP request, so there are limits. The most effective way of customizing this is using the [`instantiateFormRequestUsing`() hook](https://scribe.knuckles.wtf/laravel/hooks#instantiateformrequestusing).
- `GetFromInlineValidatorBase` uses PHP-Parser to parse the inline validator code and tries to make sense of the rules and comments. There is no full app context, the rules have to be strings, and many other limitations.

See https://scribe.knuckles.wtf/laravel/documenting/query-body-parameters#validation-rules
